<?php

namespace SystemfaBundle\Repository;

/**
 * MarcarespuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcarespuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
