<?php

namespace SystemfaBundle\Repository;

/**
 * ModelorespuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelorespuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
